server:
  port: 9000

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.73.132:3306/store_om
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: store-order
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto