spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848

  application:
    name: store-product

  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.73.130:3306/store_pms
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 10001


